/**
 * Generated by `npx convex dev`. Do not edit manually.
 * This stub is replaced by the real generated file when you run `npx convex dev`.
 */
export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
  httpAction,
} from "convex/server";
